work around for bug in exec module
inmanta/postgresql pull request #184
Opened 2022-03-14 08:27 UTC by wouterdb

# Description

Work around for bug in exec module https://github.com/inmanta/exec/issues/185

# Merge procedure

Don't use the github built-in merge, but the process described [here](https://docs.internal.inmanta.com/topics/tasks/commiting_changes_modules.html)

```sh
git pull
git checkout master
git pull
git merge --squash issue/{issue-number}-{short description}
inmanta module commit -m "{Commit Message Here}" -r
git push
git push {tag} # push the tag as well
```

Then close the PR with a reference to the commit

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [x] Changelog entry
- [X] Version number is bumped to dev version
- [x] Code is clear and sufficiently documented
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2022-03-14 08:41 UTC, arnaudsjs requested changes

2022-03-14 08:41 UTC, arnaudsjs commented on CHANGELOG.md
> +# V0.1.9
This version was already released. You should merge in the latest changes from master.

2022-03-14 08:55 UTC, arnaudsjs approved these changes

2022-03-15 08:20 UTC, wouterdb commented
merged by hand

2022-03-15 08:20 UTC, closed without merging