Add support for inmanta-module-yum 2.0.0
inmanta/postgresql pull request #315
Opened 2024-07-19 08:28 UTC by hlloreda

# Description

Added support for inmanta-module-yum 2.0.0

note: to add a changelog entry and bump the version number:
`inmanta module release --dev [--major|--minor|--patch] [--changelog-message "<your_changelog_message>"]`

# [Merge procedure](https://internal.inmanta.com/development/core/tasks/commiting-changes-modules.html)

1. merge using the merge button
2. tag and bump

```sh
git checkout master
git pull
inmanta module release
git push
git push {tag} # push the tag as well
```
3. Remove the branch

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2024-07-19 08:43 UTC, arnaudsjs requested changes
This module is not compatible with `inmanta-module-yum<2`, so we need to add a version constraint on the `inmanta-module-yum` package to make sure pip doesn't install an incompatible version of the yum module.

2024-07-19 08:43 UTC, arnaudsjs commented on model/_init.cf
> -    postgresql_service = systemd::Service(name="postgresql-{{ pg_version }}", host=self.host, state="running", onboot=true,
I think you incorrectly removed the state attribute from the `systemd:Service` entity while we should only do that for the `yum:Package` entities.

2024-07-19 11:10 UTC, arnaudsjs requested changes
I don't understand this PR. The model uses `yum::package`, which is only available in `inmanta-module-yum>=2`, but this PR adds the constraint `inmanta-module-yum<2`. So the resulting module is not going to work. I think your original PR was ok, it was just missing a constraint to make sure it would not run against `inmanta-module-yum<2`.

2024-07-22 06:58 UTC, hlloreda commented
In the near future, this module will be archived. Therefore, this pull request is not necessary.

2024-07-22 06:58 UTC, closed without merging